vanilla/vanilla-docker

images/httpd/Dockerfile, images/httpd/usr/local/apache2/conf/httpd.conf, images/php-fpm/Dockerfile
From: https://wiki.apache.org/httpd/PHP-FPM
> /path/to/your/documentroot/
IMPORTANT! This must exactly match the real filesystem location of your php files, because that is where the php-fpm daemon will look for them.
php-fpm just interprets the php files passed to it; it is not a web server, nor does it understand your web servers' namespace, virtualhost layout, or aliases.
IMPORTANT! Read the above again
Since the realpath in the php-fpm container is "srv/vanilla-repositories/vanilla" we need to use that path in httpd.conf
All vhosts will have to do the same.
=> Remove httpd dependency from php-fpm Dockerfile

docker-compose.yml, images/php-fpm/docker-entrypoint.sh
This is needed by [OAuth2](https://github.com/vanilla/stub-sso-providers/pull/6) that does a server call to /oauth2/access_token.
Also add vanilla.localhost.crt to the php container' Certificate Authority. Otherwise CURL would throw an error about the certificate being self signed.
=> Allow sso.vanilla.localhost to be resolved from the php container.

.gitignore, README.md, images/nginx/Dockerfile, mac-setup.sh, resources/etc/nginx/sites-available/advanced-embed.vanilla.localhost.conf, resources/etc/nginx/sites-available/embed.vanilla.localhost.conf, resources/etc/nginx/sites-enabled/advanced-embed.vanilla.localhost.conf, resources/etc/nginx/sites-enabled/embed.vanilla.localhost.conf
Closes #18 
Similar to stub-sso-providers, stub-embed-providers gives a simple embed implementation to vanilla-docker for testing.
Goes with https://github.com/vanilla/stub-embed-providers/pull/1
=> Add support for stub-embed-providers

README.md
Related to #32 
I ran into several problems while setting up vanilla-docker. Some of them are things that might trip up anyone who hasn't spent much time with Vanilla and Docker. This PR adds the things I was missing, up to the point of running the Vanilla installer (I had trouble there too, but then my project changed course).
The main addition is "run `composer install` in the vanilla directory"; there are also some markdown changes to better take advantage of Github's md-friendliness
=> Update installation documentation and markdown formatting

docker-compose.unit-tests.yml, docker-compose.yml
This yields a significant speedup (particularly with latency) compared to non-delegated volumes in the fpm container.
This does mean there can be a slight delay when in syncing back to host (~200ms), but this is not really significant.
All unit tests (including the alt test) still pass with this change.
=> Delegate storage on PHP-fpm containers

docker-compose.override.yml, docker-compose.unit-tests.yml, docker-compose.yml, service-sphinx.yml
Follow up of https://github.com/vanilla/vanilla-docker/pull/36
See: https://docs.docker.com/docker-for-mac/osxfs-caching/#tuning-with-consistent-cached-and-delegated-configurations
=> Mount read only volume with "cached" and write volumes with "delegated"

images/memcached/Dockerfile, images/nginx/Dockerfile, images/php-fpm/Dockerfile
Some of our plugins require the [intl](http://php.net/manual/en/book.intl.php) extension to be installed.
- Add intl extension
- Remove libmcrypt-dev dependency (It's not used by php anymore)
- Add more cleanup
- Bumb nginx version
- Lock memcached version to minor instead of patch
=> Add intl php extension and do some cleanup/updates

.gitignore, resources/etc/nginx/sites-available/comments-embed.vanilla.localhost.conf, resources/etc/nginx/sites-enabled/comments-embed.vanilla.localhost.conf
Add a config file so that we could have a local stub for testing the embedding of comments in an article or blog page.
This would close issue: https://github.com/vanilla/stub-embed-providers/issues/2
=> Add a config file for comments-embed stub.

README.md, images/php-fpm/Dockerfile
No memcached and xdebug in beta though.
Will fix https://github.com/vanilla/vanilla-docker/issues/43 when the above extension will work with PHP 7.3
=> Update php-fpm to PHP 7.3

images/php-fpm/Dockerfile
PHP's [EXIF extension](https://www.php.net/manual/en/book.exif.php) is now available to the PHP-FPM containers. This will grant improved image handling capabilities (see vanilla/vanilla#9116) to Vanilla sites running in the Docker environment.
=> Add EXIF module to PHP-FPM containers

resources/usr/local/etc/sphinx/configs-available/everything.sphinx.conf
There were duplicate attributes declared.  This error only exists on the everything.sphinx.conf.  I checked the config deployed to infrastructure and it's fine.
fixes the error being thrown when sphinx is reindexing.
`ERROR: duplicate attribute name: knowledgebaseid`
=> Removed duplicate attribute knowledgeBaseID

bootstrap.before.php
Our APIv0 test harness looks for a `/conf/vanilla.test.php` install and doesn’t actually test properly if the web server doesn’t work this way. For CI we have an alternate bootstrap, but it would be nice to be able to run tests locally too.
If devs have their own favorite localhost domain then they can either use the different config path or whitelist their domain as a PR.
=> Allow for alternate domains to install with /conf/host.php configs

images/sphinx/usr/local/etc/sphinx.conf, service-sphinx.yml
- Open up the Sphinx port so that I can run unit tests from my local (faster) brew PHP.
- Make Sphinx’s conf.d directory a proper conf.d directory that looks at all conf files inside it.
=> Enhance the sphinx config.

images/sphinx/Dockerfile, images/sphinx/root/startup.sh, images/sphinx/systemctl3.py, images/sphinx/usr/local/etc/sphinx/searchd.conf, resources/sphinx/sphinxapi.php, service-sphinx.yml
`leodido/sphinxsearch` is dead. Long live `vanillaryan/sphinxsearch`.
1. The `vanillaryan/sphinxsearch` image is now used over `leodido/sphinxsearch`. The previous image was sorely outdated. The new image uses Sphinx 3.2.1 (which has no public source code and even worse documentation than Sphinx 2).
1. The `service` command is absent in CentOS as of v7, so its usage here has been replaced with a Docker-specific version of `systemctl`, which addresses some compatibility issues.
1. Some unnecessary package installs have been removed. Other package installs have been consolidated. 
1. SphinxQL is now available on local port 9306.
Please note: until the Sphinx addon has its API incompatibility issues addressed, this update will break advanced search usage.
=> Upgrade to Sphinx v3

images/php-fpm/Dockerfile
Update the container to php 7.4.
- The new Debian release is `buster` instead of `stretch`.
- `libonig-dev` was required otherwise the compilation would fail with:
```
configure: error: Package requirements (oniguruma) were not met:
No package 'oniguruma' found
Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.
Alternatively, you may set the environment variables ONIG_CFLAGS
and ONIG_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```
- `gd` parameter were updated as per the documentation: https://hub.docker.com/_/php
=> Update php to 7.4

images/php-fpm/usr/local/etc/php/conf.d/00-php.ini
This came from a need of longer lasting local jobs on the search project.
=> Increased PHP's max execution time to 10 minutes

resources/usr/local/etc/sphinx/configs-available/everything.sphinx.conf
Update sphinx template to have knowledgeCategoryID = 0 to match some global queries
Relates to: https://github.com/vanilla/vanilla-cloud/issues/403
=> Update sphinx template to have knowledgeCategoryID = 0 

resources/usr/local/etc/sphinx/configs-available/everything.sphinx.conf
In the same vein as https://github.com/vanilla/vanilla-docker/pull/58, but a reduced set of changes.
Related https://github.com/vanilla/vanilla-cloud/pull/1030
Ensure the discussionIDs of articles are unique. I've made a very similar normalization to what is already on groups in these templates
=> Prevent articles from collapsing into discussions

service-memcached.yml
I am exposing these ports so that I can use Memcached in tests that run externally. Since this is a dev instance I feel this is a safe and sensible thing to do.
=> Expose Memcache ports to the host

README.md, images/php-fpm/Dockerfile, images/php-fpm/DockerfileXDebug, images/php-fpm/docker-entrypoint.sh
The PR adds `syslogd` to `php-fpm` with a convenient way to check it using `docker-compose logs -f` or `docker-compose up`
=> Add syslogd

resources/usr/local/etc/sphinx/configs-available/everything.sphinx.conf
Adds new locale_int to fields to sphinx templates.  Because limitations with applying string filters with sphinx, I we chose to hash the locale_int field.  Discussions\Comments\Groups get a value of any, they don't have locales, articles are treated the same using the article revision locale.
related https://github.com/vanilla/vanilla-cloud/pull/2021
=> Add locale_int to sphinx templates 

images/php-fpm/conf/10-xdebug.ini
Xdebug v3 is now _the_ Xdebug. Trying to build any new images will grab this latest version. Unfortunately, the current Xdebug config bundled here is only for v2. [Many changes were introduced with v3 that need to be accounted for.](https://xdebug.org/docs/upgrade_guide) This PR aims to get everyday step debugging up and running again.
More functionality can be added in the future, as necessary, primarily via [the xdebug.mode config](https://xdebug.org/docs/all_settings#mode).
Closes vanilla/vanilla-cloud#2587
=> Update config for Xdebug 3

resources/etc/nginx/sites-available/dev.vanilla.localhost.conf
We have some themes that have historically been symlinked in the wrong place and may have urls pointing to the wrong place if we correct them.
This nginx rule will allow us to make the change without risking any assets previously symlinked in the wrong place from breaking.
=> Add try_files for nginx to lookup badly symlinked static asset files

resources/etc/nginx/sites-available/modern-embed.vanilla.localhost.conf
Main PR: https://github.com/vanilla/vanilla-cloud/pull/5188
=> VNLA-2669: Serve php files for modern sso embed

images/php-fpm/Dockerfile
This PR updates our PHP image to the latest PHP 7.4 version.
- The iconv LD_PRELOAD hack is no longer needed.
- As a result we no longer need php7-dev or musl-dev
=> Update to use latest PHP 7.4 version

images/php-fpm/Dockerfile
Building the containers fails with the following error: 
```
#0 32.10 checking for linux/rtnetlink.h... no
#0 32.10 configure: error: rtnetlink.h is required, install the linux-headers package: apk add --update linux-headers
#0 32.12 ERROR: `/tmp/pear/temp/xdebug/configure --with-php-config=/usr/local/bin/php-config' failed
------
failed to solve: process "/bin/sh -c apk add --update --no-cache $PHPIZE_DEPS        icu         icu-dev         freetype libjpeg-turbo libpng libwebp libxpm         freetype-dev libjpeg-turbo-dev libpng-dev libwebp-dev libxpm-dev         oniguruma         oniguruma-dev         libmemcached         libmemcached-dev         rsyslog     && pecl install apcu     && pecl install memcached     && pecl install xdebug     && docker-php-ext-enable apcu     && …
```
=> Fix build failing by adding missing requirement linux-headers
